title: Chi's Lab Notes
author: Chi Zhou
email: zhouchi24@mails.ucas.ac.cn

url: https://qingyuye.github.io
baseurl: ""

description: >
  Bioinformatics · Single-cell Genomics · Computational Biology

permalink: /:slug.html

favicon: "logo.png"

remote_theme: riggraz/no-style-please

theme_config:
  appearance: "auto"

  back_home_text: ".."

  date_format: "%Y-%m-%d"

  show_description: true

  lowercase_titles: false

plugins:
  - jekyll-feed
  - jekyll-seo-tag
